/**
 * Plain-language glossary. Basic terms show in every view; `advanced` terms
 * show in the Advanced & Developer view. General definitions only: nothing
 * here is a claim about a specific tool.
 */
import type { Locale } from '@/i18n/config';

export interface GlossaryTerm {
  id: string;
  advanced?: boolean;
  text: Partial<Record<Locale, { term: string; def: string }>>;
}

export const GLOSSARY: GlossaryTerm[] = [
  { id: 'ai', text: { nl: { term: 'AI (kunstmatige intelligentie)', def: 'Computerprogramma’s die taken doen waarvoor je normaal menselijk denkwerk nodig hebt, zoals tekst schrijven, beelden herkennen of vragen beantwoorden. Ze leren dat van heel veel voorbeelden.' }, en: { term: 'AI (artificial intelligence)', def: 'Computer programs that do tasks that normally need human thinking, such as writing text, recognising images or answering questions. They learn this from very many examples.' } } },
  { id: 'generative-ai', text: { nl: { term: 'Generatieve AI', def: 'AI die iets nieuws maakt: tekst, afbeeldingen, muziek, video of code, op basis van jouw beschrijving.' }, en: { term: 'Generative AI', def: 'AI that creates something new: text, images, music, video or code, based on your description.' } } },
  { id: 'llm', text: { nl: { term: 'Taalmodel (LLM)', def: 'Het ‘brein’ achter een AI-chatbot. Het heeft enorm veel tekst gelezen en voorspelt woord voor woord een passend antwoord. LLM staat voor large language model.' }, en: { term: 'Language model (LLM)', def: 'The ‘brain’ behind an AI chatbot. It has read enormous amounts of text and predicts a fitting answer word by word. LLM stands for large language model.' } } },
  { id: 'assistant', text: { nl: { term: 'AI-assistent (chatbot)', def: 'Een programma waarmee je in gewone taal chat: je stelt een vraag of geeft een opdracht en krijgt een antwoord.' }, en: { term: 'AI assistant (chatbot)', def: 'A program you chat with in plain language: you ask a question or give an instruction and get an answer.' } } },
  { id: 'prompt', text: { nl: { term: 'Prompt', def: 'De vraag of opdracht die je aan AI geeft. Hoe duidelijker de prompt, met doel, context en gewenste vorm, hoe beter het resultaat.' }, en: { term: 'Prompt', def: 'The question or instruction you give AI. The clearer the prompt, with goal, context and desired format, the better the result.' } } },
  { id: 'hallucination', text: { nl: { term: 'Hallucinatie', def: 'Als AI zelfverzekerd iets beweert dat niet klopt, zoals een verzonnen bron, datum of cijfer. Controleer daarom belangrijke feiten altijd.' }, en: { term: 'Hallucination', def: 'When AI confidently states something that is not true, such as an invented source, date or number. Always check important facts.' } } },
  { id: 'multimodal', text: { nl: { term: 'Multimodaal', def: 'AI die meer dan één soort invoer begrijpt, bijvoorbeeld tekst én afbeeldingen, geluid of video.' }, en: { term: 'Multimodal', def: 'AI that understands more than one kind of input, for example text and images, sound or video.' } } },
  { id: 'agent', text: { nl: { term: 'AI-agent', def: 'AI die niet alleen antwoord geeft, maar zelf stappen uitvoert om een doel te bereiken, zoals iets opzoeken, een bestand aanpassen of een app bedienen. Laat een agent nooit zonder controle belangrijke dingen doen.' }, en: { term: 'AI agent', def: 'AI that does not just answer but carries out steps to reach a goal, such as looking something up, editing a file or operating an app. Never let an agent do important things unchecked.' } } },
  { id: 'automation', text: { nl: { term: 'Automatisering (workflow)', def: 'Een vaste reeks stappen die automatisch wordt uitgevoerd, bijvoorbeeld: nieuw formulier → gegevens in een spreadsheet → bevestigingsmail.' }, en: { term: 'Automation (workflow)', def: 'A fixed series of steps that runs by itself, for example: new form → data into a spreadsheet → confirmation e-mail.' } } },
  { id: 'no-code', text: { nl: { term: 'No-code', def: 'Iets bouwen, zoals een website, app of automatisering, zonder te programmeren: met slepen, klikken en gewone taal.' }, en: { term: 'No-code', def: 'Building something, such as a website, app or automation, without programming: by dragging, clicking and plain language.' } } },
  { id: 'freemium', text: { nl: { term: 'Freemium', def: 'Een dienst met een gratis versie met beperkingen en betaalde abonnementen met meer mogelijkheden.' }, en: { term: 'Freemium', def: 'A service with a limited free version and paid plans with more features.' } } },
  { id: 'credits', text: { nl: { term: 'Credits', def: 'Een tegoed dat je verbruikt per AI-opdracht, zoals per afbeelding of per minuut video. Kijk hoeveel credits je per maand krijgt en wat extra credits kosten.' }, en: { term: 'Credits', def: 'An allowance you use up per AI task, such as per image or per minute of video. Check how many credits you get per month and what extra credits cost.' } } },
  { id: 'per-seat', text: { nl: { term: 'Prijs per gebruiker', def: 'Je betaalt per persoon die de dienst gebruikt. Met een team van vijf betaal je dus vijf keer de prijs.' }, en: { term: 'Per-user price', def: 'You pay per person using the service. A team of five pays five times the price.' } } },
  { id: 'watermark', text: { nl: { term: 'Watermerk', def: 'Een logo of tekst die een dienst in je afbeelding of video zet, vaak bij gratis versies.' }, en: { term: 'Watermark', def: 'A logo or text a service puts on your image or video, often on free plans.' } } },
  { id: 'commercial-use', text: { nl: { term: 'Commercieel gebruik', def: 'Iets gebruiken om geld mee te verdienen, bijvoorbeeld in reclame of voor klanten. Niet elk abonnement staat dat toe; lees de voorwaarden.' }, en: { term: 'Commercial use', def: 'Using something to make money, for example in ads or for clients. Not every plan allows it; read the terms.' } } },
  { id: 'transcription', text: { nl: { term: 'Transcriptie', def: 'Gesproken woorden automatisch omzetten in tekst, bijvoorbeeld van een interview of vergadering.' }, en: { term: 'Transcription', def: 'Automatically turning spoken words into text, for example from an interview or meeting.' } } },
  { id: 'tts', text: { nl: { term: 'Tekst naar spraak', def: 'Een geschreven tekst laten voorlezen door een computerstem.' }, en: { term: 'Text to speech', def: 'Having a written text read aloud by a computer voice.' } } },
  { id: 'voice-cloning', text: { nl: { term: 'Stem klonen', def: 'Een AI-stem maken die klinkt als een bestaand persoon. Doe dit alleen met je eigen stem of met uitdrukkelijke toestemming.' }, en: { term: 'Voice cloning', def: 'Creating an AI voice that sounds like a real person. Only do this with your own voice or explicit consent.' } } },
  { id: 'deepfake', text: { nl: { term: 'Deepfake', def: 'Door AI gemaakte beelden, video of geluid die echt lijken, maar nep zijn. De Europese AI-verordening verplicht om te vermelden dat zulke inhoud door AI is gemaakt.' }, en: { term: 'Deepfake', def: 'AI-made images, video or audio that look real but are fake. The EU AI Act requires disclosing that such content is AI-generated.' } } },
  { id: 'dubbing', text: { nl: { term: 'Nasynchronisatie (dubbing)', def: 'Een video in een andere taal laten inspreken, soms met passende lipbewegingen.' }, en: { term: 'Dubbing', def: 'Voicing a video in another language, sometimes with matching lip movements.' } } },
  { id: 'upscaling', text: { nl: { term: 'Upscalen', def: 'Een afbeelding groter en scherper maken met AI, zonder dat hij blokkerig wordt.' }, en: { term: 'Upscaling', def: 'Making an image larger and sharper with AI without it becoming blocky.' } } },
  { id: 'avatar', text: { nl: { term: 'AI-avatar', def: 'Een digitale presentator die jouw tekst in een video uitspreekt, zonder dat je zelf hoeft te filmen.' }, en: { term: 'AI avatar', def: 'A digital presenter that speaks your text in a video, without you filming yourself.' } } },
  { id: 'local', text: { nl: { term: 'Lokaal draaien', def: 'AI op je eigen computer gebruiken in plaats van via internet. Je gegevens blijven dan op je apparaat.' }, en: { term: 'Running locally', def: 'Using AI on your own computer instead of over the internet. Your data then stays on your device.' } } },
  { id: 'training-data', text: { nl: { term: 'Training op jouw data', def: 'Sommige diensten gebruiken wat je invoert om hun AI verder te trainen. Vaak kun je dat uitzetten; kijk in de instellingen of de voorwaarden.' }, en: { term: 'Training on your data', def: 'Some services use what you enter to further train their AI. You can often switch it off; check the settings or terms.' } } },
  { id: 'gdpr', text: { nl: { term: 'AVG (GDPR)', def: 'De Europese privacywet. Die bepaalt wat bedrijven met persoonsgegevens mogen doen. Voer geen persoonsgegevens van anderen in zonder goede reden.' }, en: { term: 'GDPR', def: 'The European privacy law. It sets what companies may do with personal data. Do not enter other people’s personal data without good reason.' } } },
  { id: 'dpa', text: { nl: { term: 'Verwerkersovereenkomst', def: 'Een afspraak tussen jouw bedrijf en een dienst over hoe die met persoonsgegevens omgaat. Verplicht onder de AVG als een dienst persoonsgegevens voor jou verwerkt.' }, en: { term: 'Data processing agreement (DPA)', def: 'An agreement between your business and a service on how it handles personal data. Required under the GDPR when a service processes personal data for you.' } } },
  { id: 'eu-data', text: { nl: { term: 'Dataopslag in de EU', def: 'Je gegevens worden opgeslagen op servers binnen de Europese Unie. Voor sommige organisaties is dat een eis.' }, en: { term: 'EU data residency', def: 'Your data is stored on servers inside the European Union. Some organisations require this.' } } },
  { id: 'ai-act', text: { nl: { term: 'AI-verordening (AI Act)', def: 'De Europese wet voor AI. Die stelt regels op basis van risico, zoals verboden toepassingen en een meldplicht voor deepfakes.' }, en: { term: 'AI Act', def: 'The European law on AI. It sets rules based on risk, such as banned uses and a disclosure duty for deepfakes.' } } },
  { id: 'api', advanced: true, text: { nl: { term: 'API', def: 'Een koppeling waarmee software met een dienst praat. Via een API kun je AI in je eigen app of automatisering gebruiken, meestal betaald per gebruik.' }, en: { term: 'API', def: 'A connection that lets software talk to a service. Through an API you can use AI in your own app or automation, usually paid per use.' } } },
  { id: 'api-key', advanced: true, text: { nl: { term: 'API-sleutel', def: 'Een geheime code waarmee je toegang krijgt tot een API. Deel hem nooit en zet hem nooit in openbare code of in de browser.' }, en: { term: 'API key', def: 'A secret code that gives access to an API. Never share it or put it in public code or the browser.' } } },
  { id: 'token', advanced: true, text: { nl: { term: 'Token', def: 'Een stukje tekst (vaak een deel van een woord) waarin een taalmodel rekent. API-prijzen en limieten worden meestal per token uitgedrukt.' }, en: { term: 'Token', def: 'A piece of text (often part of a word) a language model works in. API prices and limits are usually expressed per token.' } } },
  { id: 'context-window', advanced: true, text: { nl: { term: 'Contextvenster', def: 'Hoeveel tekst een taalmodel tegelijk kan meenemen: je vraag, het gesprek en eventuele documenten. Is het vol, dan ‘vergeet’ het model het begin.' }, en: { term: 'Context window', def: 'How much text a language model can take into account at once: your question, the conversation and any documents. When full, the model ‘forgets’ the beginning.' } } },
  { id: 'open-weights', advanced: true, text: { nl: { term: 'Open model (open gewichten)', def: 'Een AI-model dat je zelf mag downloaden en draaien. Let op de licentie: niet elk open model mag zomaar commercieel worden gebruikt.' }, en: { term: 'Open model (open weights)', def: 'An AI model you may download and run yourself. Check the licence: not every open model may be used commercially.' } } },
  { id: 'rag', advanced: true, text: { nl: { term: 'RAG (chatten met je eigen documenten)', def: 'Een techniek waarbij AI eerst relevante stukken uit jouw documenten opzoekt en daarop zijn antwoord baseert. Zo worden antwoorden specifieker en controleerbaar.' }, en: { term: 'RAG (chatting with your own documents)', def: 'A technique where AI first retrieves relevant passages from your documents and bases its answer on them, making answers more specific and checkable.' } } },
  { id: 'fine-tuning', advanced: true, text: { nl: { term: 'Fine-tuning', def: 'Een bestaand model extra trainen op je eigen voorbeelden, zodat het beter past bij een specifieke taak of schrijfstijl.' }, en: { term: 'Fine-tuning', def: 'Training an existing model further on your own examples so it fits a specific task or writing style better.' } } },
  { id: 'embeddings', advanced: true, text: { nl: { term: 'Embeddings', def: 'Een manier om tekst om te zetten in getallen die de betekenis vangen, zodat software kan zoeken op betekenis in plaats van op exacte woorden.' }, en: { term: 'Embeddings', def: 'A way to turn text into numbers that capture meaning, so software can search by meaning instead of exact words.' } } },
  { id: 'status', text: { nl: { term: 'Gecontroleerd, Ondersteund, Onbevestigd', def: 'Onze statussen bij prijzen en feiten. Gecontroleerd: letterlijk bevestigd op de officiële bron. Ondersteund: meerdere bronnen komen overeen. Onbevestigd: nog niet op de officiële site bevestigd.' }, en: { term: 'Verified, Supported, Unverified', def: 'Our statuses for prices and facts. Verified: confirmed word for word on the official source. Supported: several sources agree. Unverified: not yet confirmed on the official site.' } } },
  { id: 'affiliate', text: { nl: { term: 'Affiliatelink', def: 'Een link waarmee een website een vergoeding kan krijgen als je iets koopt. Bij ons beïnvloedt dat nooit de volgorde van tools en we vermelden het altijd.' }, en: { term: 'Affiliate link', def: 'A link through which a website may earn a fee if you buy something. On our site it never affects the order of tools and we always disclose it.' } } },
];

export function glossaryText(term: GlossaryTerm, locale: Locale): { term: string; def: string } | null {
  return term.text[locale] ?? term.text.en ?? term.text.nl ?? null;
}
