/**
 * Builds src/generated/logos.ts from data/logos.json and the simple-icons
 * package (a dev dependency), so the site serves the marks itself and never
 * depends on the package or another host at runtime.
 *
 *   npx tsx scripts/generate-logos.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

interface Icon {
  title: string;
  slug: string;
  hex: string;
  path: string;
  source: string;
}

const require = createRequire(import.meta.url);
const config = JSON.parse(readFileSync('data/logos.json', 'utf8')) as { version: string; license: string; logos: Record<string, string> };
const pkg = JSON.parse(readFileSync('node_modules/simple-icons/package.json', 'utf8')) as { version: string };
if (pkg.version !== config.version) throw new Error(`simple-icons ${pkg.version} is installed; data/logos.json expects ${config.version}`);
const icons = require('simple-icons') as Record<string, Icon>;
const bySlug = new Map(Object.values(icons).filter((i) => i && i.slug).map((i) => [i.slug, i]));

const entries = Object.entries(config.logos).sort(([a], [b]) => a.localeCompare(b));
const lines = entries.map(([tool, slug]) => {
  const icon = bySlug.get(slug);
  if (!icon) throw new Error(`simple-icons has no "${slug}" (for ${tool})`);
  return `  ${JSON.stringify(tool)}: { title: ${JSON.stringify(icon.title)}, path: ${JSON.stringify(icon.path)} },`;
});

const out = `// Generated by scripts/generate-logos.ts from simple-icons@${config.version} (${config.license}). Do not edit.
// The marks are trademarks of their owners and only identify the tool (data/logos.json).

export interface ToolLogo {
  title: string;
  /** SVG path in a 24×24 box. */
  path: string;
}

export const LOGOS: Record<string, ToolLogo> = {
${lines.join('\n')}
};
`;
writeFileSync('src/generated/logos.ts', out);
console.log(`[logos] ${entries.length} logos → src/generated/logos.ts`);
