/**
 * Builds src/generated/logos.ts from data/logos.json and the simple-icons
 * package (a dev dependency), so the site serves the marks itself and never
 * depends on the package or another host at runtime.
 *
 *   npx tsx scripts/generate-logos.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

interface Icon {
  title: string;
  slug: string;
  hex: string;
  path: string;
  source: string;
}

const require = createRequire(import.meta.url);
const config = JSON.parse(readFileSync('data/logos.json', 'utf8')) as { version: string; license: string; logos: Record<string, string> };
const pkg = JSON.parse(readFileSync('node_modules/simple-icons/package.json', 'utf8')) as { version: string };
if (pkg.version !== config.version) throw new Error(`simple-icons ${pkg.version} is installed; data/logos.json expects ${config.version}`);
const icons = require('simple-icons') as Record<string, Icon>;
const bySlug = new Map(Object.values(icons).filter((i) => i && i.slug).map((i) => [i.slug, i]));

/** WCAG contrast of two #rrggbb colours. */
function contrast(a: string, b: string): number {
  const lum = (hex: string) => {
    const [r, g, bl] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255).map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
    return 0.2126 * r! + 0.7152 * g! + 0.0722 * bl!;
  };
  const [x, y] = [lum(a), lum(b)];
  return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05);
}
// The mark's tile in each theme (--surface-2 with a light world tint); a brand colour must reach 3:1 there.
const TILE = { light: '#f4f0ea', dark: '#211f2e' };
const brand = (hex: string, tile: string) => (contrast(`#${hex}`, tile) >= 3 ? `#${hex.toLowerCase()}` : null);

const entries = Object.entries(config.logos).sort(([a], [b]) => a.localeCompare(b));
const lines = entries.map(([tool, slug]) => {
  const icon = bySlug.get(slug);
  if (!icon) throw new Error(`simple-icons has no "${slug}" (for ${tool})`);
  const light = brand(icon.hex, TILE.light);
  const dark = brand(icon.hex, TILE.dark);
  return `  ${JSON.stringify(tool)}: { title: ${JSON.stringify(icon.title)}, light: ${JSON.stringify(light)}, dark: ${JSON.stringify(dark)}, path: ${JSON.stringify(icon.path)} },`;
});

const out = `// Generated by scripts/generate-logos.ts from simple-icons@${config.version} (${config.license}). Do not edit.
// The marks are trademarks of their owners and only identify the tool (data/logos.json).

export interface ToolLogo {
  title: string;
  /** Brand colour where it reaches 3:1 against the mark's tile in that theme, else null (ink). */
  light: string | null;
  dark: string | null;
  /** SVG path in a 24×24 box. */
  path: string;
}

export const LOGOS: Record<string, ToolLogo> = {
${lines.join('\n')}
};
`;
writeFileSync('src/generated/logos.ts', out);
console.log(`[logos] ${entries.length} logos → src/generated/logos.ts`);
